<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_icon-trash</name>
   <tag></tag>
   <elementGuidId>281c4caf-67b4-4bc5-b84c-f9b1f265e9c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title = 'Remove' and @class = 'icon-trash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:mw.cart.remove('33');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_checkout_cart_checkout&quot;)/div[@class=&quot;mw-cart mw-cart-big mw-cart-cart_checkout_cart_checkout&quot;]/table[@class=&quot;table table-bordered table-striped mw-cart-table mw-cart-table-medium mw-cart-big-table&quot;]/tbody[1]/tr[@class=&quot;mw-cart-item mw-cart-item-33&quot;]/td[6]/a[@class=&quot;icon-trash&quot;]</value>
   </webElementProperties>
</WebElementEntity>
